// Generated by `py lib.py build`. The pages docsify's search
// plugin indexes; see index.html.
window.LIBRARY_PATHS = [
"/README.md",
"/INBOX.md",
"/indexes/by-date.md",
"/indexes/by-topic.md",
"/indexes/by-author.md",
"/indexes/by-rating.md",
"/topics/engineering-blogs.md",
"/library/2026/2026-08-30-qwen3-8-flash-next.md",
"/library/2026/2026-08-30-quoting-paul-dix.md",
"/library/2023/2026-08-30-memgpt-towards-llms-as-operating-systems.md",
"/library/2026/2026-08-30-making-large-language-models-work-for-you.md",
"/library/2026/2026-08-30-just-a-rumour-of-a-bug-is-enough-to-find-a-security-exploit.md",
"/library/2026/2026-08-30-introducing-hy4-preview.md",
"/library/2026/2026-08-30-breaking-claude-code-opus-5-auto-mode.md"
];
